apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    project: roboshop
    component: mongodb
    tier: database
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      component: mongodb
      tier: database
  template:
    metadata:
      labels:
       project: roboshop
       component: mongodb
       tier: database
    spec:
      containers:
      - name: mongodb
        image: joindevops/mongodb:v1
