apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: roboshop
  labels:
    project: roboshop
    component: mysql
    tier: database
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      component: mysql
      tier: database
  template:
    metadata:
      labels:
       project: roboshop
       component: mysql
       tier: database
    spec:
      containers:
      - name: mysql
        image: joindevops/mysql:v1
        imagePullPolicy: Always

        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "admin"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "roboshop123"

        ports:
        - containerPort: 3306

        readinessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 10
          periodSeconds: 10

        livenessProbe:
          tcpSocket:
            port: 3306   # FIXED
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: roboshop
spec:
  selector:
    project: roboshop
    component: mysql
    tier: database
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
