apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: roboshop
  labels:
    project: roboshop
    component: redis
    tier: database
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      component: redis
      tier: database
  template:
    metadata:
      labels:
        project: roboshop
        component: redis
        tier: database
    spec:
      containers:
      - name: redis
        image: redis:7.0
        imagePullPolicy: Always

        command: ["redis-server"]
        args: ["--requirepass", "roboshop123"]

        env:
        - name: REDIS_PASSWORD
          value: "roboshop123"

        ports:
        - containerPort: 6379

        readinessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 10
          periodSeconds: 10

        livenessProbe:
          tcpSocket:
            port: 6379   # FIXED
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: roboshop
spec:
  selector:
    project: roboshop
    component: redis
    tier: database
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
